apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podcast-helm.fullname" . }}
  labels:
    {{- include "podcast-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "podcast-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "podcast-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podcast-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init
        image: shivani446/podcastwala:latest
        ports:
        - containerPort: 8181
        env:
            - name: DB_DATABASE
              value: forge
            - name: DB_HOST
              value: podcast-mariadb
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: forge
        command: ["/bin/sh", "-c"]
        args: ["php artisan migrate --force"]
      containers:
        - env:
            - name: DB_DATABASE
              value: forge
            - name: DB_HOST
              value: podcast-mariadb
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: forge
          image: shivani446/podcastwala:latest
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 8181
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
